version: "3.7"
services:
  api-service:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: project-api
    container_name: project-api-server
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 5000:5000
    depends_on:
      - db-service
    networks:
      - project-network
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      DB_CONN: mongodb://db-service:27017/
      DB_NAME: db-project

  db-service:
    image: mongo:4.4.11-rc0-focal
    volumes:
      - data-volume:/data/db
    logging:
      driver: none
    ports:
      - "27017:27017"
    networks:
      - project-network

  web-service:
    build:
      context: ./web/
      dockerfile: Dockerfile
    image: project-client
    container_name: project-web-client
    stdin_open: true
    command: npm start
    volumes:
      - ./web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api-service
    ports:
      - "3000:3000"
    networks:
      - project-network
    environment:
      REACT_APP_API: http://localhost:5000/api/
      CHOKIDAR_USEPOLLING: "true"

networks:
  project-network:
    driver: bridge

volumes:
  data-volume:
